name: Build

env:
  SLN_PATH: Source/Assemblies/MMeds/MMeds.sln

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    # build MMeds.dll

    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - run: dotnet restore ${{ env.SLN_PATH }}
    - run: dotnet build ${{ env.SLN_PATH }} --configuration Release --no-restore
    - run: dotnet test ${{ env.SLN_PATH }} --no-restore --verbosity normal

    # xmllint all XML files

    - run: sudo apt install -y libxml2-utils
    - uses: tj-actions/glob@v17
      id: glob
      with:
        files: |
          **/*.xml
    - run: |
        xmllint --noout ${{ steps.glob.outputs.paths }}

    # upload the mod as an artifact

    - uses: actions/upload-artifact@v3
      with:
        name: ManyMedicines
        path: |
          ${{ github.workspace }}
          !.git
          !.github
          !.gitignore
          !Source
