name: Build MMeds.dll

env:
  SLN_PATH: Source/Assemblies/MMeds/MMeds.sln

on:
  pull_request:
    paths:
      - 'Source/Assemblies/MMeds/*.cs'
      - 'Source/Assemblies/MMeds/*.csproj'
      - 'Source/Assemblies/MMeds/*.sln'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - run: dotnet restore ${{ env.SLN_PATH }}
    - run: dotnet build ${{ env.SLN_PATH }} --configuration Debug --no-restore
    - run: dotnet test ${{ env.SLN_PATH }} --no-restore --verbosity normal
    - uses: actions/upload-artifact@v3
      with:
        name: MMeds.dll
        path: 1.4/Assemblies/MMeds.*
