name: CI

env:
  SOLUTION_PATH: Source/Assemblies/MMeds/MMeds.sln

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**.xml'
      - '**.sln'
      - '**.csproj'
      - '**.cs'
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - main
    paths:
      - '**.xml'
      - '**.sln'
      - '**.csproj'
      - '**.cs'

jobs:

  ci:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - run: dotnet restore ${{ env.SOLUTION_PATH }}
    - run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Debug --no-restore
    - run: dotnet test ${{ env.SOLUTION_PATH }} --no-restore --verbosity normal

    - uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: libxml2-utils
    - uses: tj-actions/glob@v17
      id: glob
      with:
        files: |
          **/*.xml
    - run: |
        for i in '${{ steps.glob.outputs.paths }}'; do xmllint --noout $i; done