name: Release

env:
  MOD_NAME: ManyMedicines
  SOLUTION_PATH: Source/Assemblies/MMeds/MMeds.sln
  FILES_TO_INCLUDE: 1.4 About Common LICENSE LoadFolders.xml

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:

  bump-version:

    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      skip: ${{ steps.bumpr.outputs.skip }}
      current_version: ${{ steps.bumpr.outputs.current_version }}
      next_version: ${{ steps.bumpr.outputs.next_version }}
      message: ${{ steps.bumpr.outputs.message }}

    if: github.event.pull_request.merged == true
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: haya14busa/action-bumpr@v1.8.1
      id: bumpr

  build:

    runs-on: ubuntu-latest
    permissions: write-all
    needs: bump-version

    if: needs.bump-version.outputs.skip == false
    steps:

    - uses: actions/checkout@v3
      with:
        ref: ${{ needs.bump-version.outputs.next_version }}
        fetch-depth: 0

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - run: dotnet restore ${{ env.SOLUTION_PATH }}
    - run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

    - uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: libxml2-utils
    - uses: tj-actions/glob@v17
      id: glob
      with:
        files: |
          **/*.xml
    - run: |
        for i in '${{ steps.glob.outputs.paths }}'; do xmllint --noout $i; done

    - uses: mikepenz/release-changelog-builder-action@v4
      id: build_changelog
      with:
        configuration: ".github/workflows/configuration/release-changelog-builder.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        zip -r '${{ env.MOD_NAME }}-${{ needs.bump-version.outputs.next_version }}.zip' ${{ env.FILES_TO_INCLUDE }}

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ github.token }}
        artifactErrorsFailBuild: true
        draft: false
        makeLatest: true
        body: ${{ steps.build_changelog.outputs.changelog }}
        artifacts: '${{ env.MOD_NAME }}-${{ needs.bump-version.outputs.next_version }}.zip'
        artifactContentType: 'application/zip'
        tag: ${{ needs.bump-version.outputs.next_version }}