name: Require Label on Pull Request

on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:

  require-labels:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:

    - uses: mheap/github-action-required-labels@v5
      with:
        mode: exactly
        count: 1
        labels: "bug, chore, enhancement"
        add_comment: true
        message: "This pull request cannot be merged because {{ errorString }} {{ count }} of `{{ provided }}` is required."